config/routes.rb
Rush::Application.routes.draw do
  devise_for :models

	resources :admins
	
	resource :home

  root :to => "home#index"

  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title><%= h(yield(:title) || "Devise") %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag 'application' %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      <%- end -%>

      <p><%= link_to 'Home', root_path %></p>

      <% if user_signed_in? -%>
        <div id="user_login_box" style="float:right">
          <%= current_user.email %> |
          <%= link_to 'My info', edit_user_registration_path %> |
          <%= link_to 'Sign out', destroy_user_session_path %>
        </div>
      <% end -%>
      <% if admin_signed_in? -%>
        <div id="admin_login_box" style="float:left">
          <%= current_admin.email %> |
          <%= link_to 'Admin section', admins_path %> |
          <%= link_to 'Sign out', destroy_admin_session_path %>
        </div>
      <% end -%>
      <div style="clear:both"></div>

      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>

      <%= yield %>
    </div>
    <%= javascript_include_tag :defaults %>
  </body>
</html>